<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <AssemblyName>SimpleBackup</AssemblyName>
    <Description>Valheim Simple Backup Mod</Description>
    <Version>0.1.0</Version>
    <ValheimInstallPath>C:\Program Files (x86)\Steam\steamapps\common\Valheim</ValheimInstallPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);MSB3277</NoWarn>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
    </RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(ValheimInstallPath)\BepInEx\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(ValheimInstallPath)\BepInEx\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MonoMod.RuntimeDetour">
      <HintPath>$(ValheimInstallPath)\BepInEx\core\MonoMod.RuntimeDetour.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>$(ValheimInstallPath)\BepInEx\core\MonoMod.Utils.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="assembly_valheim">
      <HintPath>$(ValheimInstallPath)\valheim_Data\Managed\assembly_valheim.dll</HintPath>
    </Reference>
    <Reference Include="assembly_guiutils">
      <HintPath>$(ValheimInstallPath)\valheim_Data\Managed\assembly_guiutils.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ValheimInstallPath)\valheim_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ValheimInstallPath)\valheim_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(ValheimInstallPath)\valheim_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(ValheimInstallPath)\valheim_Data\Managed\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(ValheimInstallPath)\valheim_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(ValheimInstallPath)\valheim_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(ValheimInstallPath)\valheim_Data\Managed\Unity.TextMeshPro.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
